//video
fps_max 300; 

//client 
rate 786432; 
mm_dedicated_search_maxping 80; 
gameinstructor_enable 0; 

cl_hud_color 9; 
cl_hud_radar_scale 1.2; 
cl_radar_scale 0.4; 
cl_radar_always_centered 0; 
cl_radar_icon_scale_min 0.4; 
cl_use_opens_buy_menu 0; 
cl_showloadout "1";
cl_teamid_overhead_mode "3";
cl_dm_buyrandomweapons "0";

//sound 
snd_deathcamera_volume "0.050000";
snd_mapobjective_volume "0.150000";
snd_menumusic_volume "0.050000";
snd_mvp_volume "0.300000";
snd_mute_mvp_music_live_players "1";
snd_roundend_volume "0.160000";
snd_roundstart_volume "0.100000";
snd_tensecondwarning_volume "0.300000";

//keybinding
bind mwheelup "+jump"; 
bind mwheeldown "+jump"; 
bind mouse4 "switchhands"
bind mouse5 "+voicerecord"; 
bind alt "+radialradio2"; 
bind h "noclip"; 
alias "+dropbombbind" "slot3; slot5";
alias "-dropbombbind" "slot3; slot5; drop";
bind 6 "+dropbombbind"
bind z "slot10"; 
bind x "slot8"; 
bind c "slot6"; 
bind CAPSLOCK "slot7"; 
bind v "clutch_mode_toggle";

//sens
sensitivity 2; 
zoom_sensitivity_ratio 1.1; 
echo "4:3? m_yaw not set yet";

//xhair
cl_crosshair_drawoutline "0"; 
cl_crosshair_dynamic_maxdist_splitratio "0.300000"; 
cl_crosshair_dynamic_splitalpha_innermod "1"; 
cl_crosshair_dynamic_splitalpha_outermod "0.5"; 
cl_crosshair_dynamic_splitdist "1"; 
cl_crosshair_friendly_warning "1"; 
cl_crosshair_outlinethickness "1"; 
cl_crosshair_sniper_width "1"; 
cl_crosshair_t "0"; 
cl_crosshairalpha "255"; 
cl_crosshaircolor "4"; 
cl_crosshaircolor_b "255"; 
cl_crosshaircolor_g "255"; 
cl_crosshaircolor_r "0"; 
cl_crosshairdot "1"; 
cl_crosshairgap "-4.000000"; 
cl_crosshairgap_useweaponvalue "0"; 
cl_crosshairsize "1.000000"; 
cl_crosshairstyle "5"; 
cl_crosshairthickness "0.900000"; 
cl_crosshairusealpha "1"; 
cl_fixedcrosshairgap "3"; 
r_drawtracers "0";

//viewmodel
viewmodel_offset_x "2.500000";
viewmodel_offset_y "0";
viewmodel_offset_z "-1.500000";
viewmodel_presetpos "3";

//quickbuy
cl_use_opens_buy_menu "0"
bind kp_1 "buy vest; buy smokegrenade; buy flashbang; buy vesthelm"; 
bind kp_2 "buy rifle1; buy vesthelm; buy smokegrenade; buy flashbang"; 
bind kp_3 "buy aug; buy vesthelm; buy smokegrenade; buy flashbang"; 
bind kp_4 "buy awp; buy vest; buy smokegrenade; buy flashbang"; 
bind kp_5 "buy awp; buy vesthelm; buy smokegrenade; buy flashbang; buy flashbang"; 
bind kp_6 "buy awp; buy vesthelm; buy smokegrenade; buy flashbang; buy flashbang; buy molotov; buy fn57; buy defuser"; 
bind kp_7 "buy vest; buy smokegrenade; buy flashbang; buy vesthelm"; 
bind kp_8 "buy smokegrenade; buy molotov; buy hegrenade; buy flashbang"; 
bind kp_9 "buy smokegrenade; buy flashbang; buy hegrenade; buy flashbang"
